// AP Lang Video Checklist data — extracted from AP_Lang_Video_Checklist.xlsx
window.AP_LANG_DATA = {
  meta: {
    title: "AP Lang FRQ Gap Plan",
    subtitle: "Targeted prep for topics not tested since 2020",
  },
  skillKey: {
    CLE:   { name: "Claims & Evidence (Reading)",    weight: "13–16%", tier: "HIGH" },
    REO:   { name: "Reasoning & Org. (Reading)",     weight: "13–16%", tier: "HIGH" },
    RHS:   { name: "Rhetorical Situation (Reading)", weight: "11–14%", tier: "MED" },
    STY:   { name: "Style (Reading)",                weight: "11–14%", tier: "MED" },
  },
  topics: [
    {
      id: "unknown",
      title: "Exploring the unknown",
      subtitle: "Risk-taking & venturing into uncertainty",
      lastTested: 2020,
      yearsAbsent: "5+",
      frqType: "Argument",
      priority: "HIGH",
      skills: ["CLE", "REO"],
      summary: "Open-ended argument prompts asking students to take a position on the value of pursuing the unknown. Demands a tight line of reasoning without provided sources.",
      videos: [
        {
          id: "u1",
          title: "Establishing a line of reasoning — wind farm synthesis",
          channel: "Coach Hall Writes",
          duration: "12 min",
          url: "https://www.youtube.com/watch?v=qvY11BTnv4M",
          why: "Uses wind farm prompt to teach REO — same skills transfer directly to exploration / risk argument essays.",
        },
        {
          id: "u2",
          title: "Q3 full body paragraph: master the argument essay",
          channel: "YouTube · Nov 2025",
          duration: "18 min",
          url: "https://www.youtube.com/watch?v=JVUlW3TW2A8",
          why: "Walks through a complete argument paragraph using a real exam prompt — directly applicable to open-ended prompts like the unknown / risk theme.",
        },
        {
          id: "u3",
          title: "Argument essay outline guide (with video)",
          channel: "coachhallwrites.com",
          duration: "Article + video",
          url: "https://coachhallwrites.com/argument-essay-outline/",
          why: "Blueprint for planning any argument FRQ — especially useful for open-ended prompts with no provided sources.",
        },
      ],
    },
    {
      id: "identity",
      title: "National identity",
      subtitle: "Political fragmentation & civic argument",
      lastTested: 2022,
      yearsAbsent: "3+",
      frqType: "Argument",
      priority: "HIGH",
      skills: ["CLE", "REO"],
      summary: "Polarizing civic prompts requiring measured claim qualification — students must navigate competing identities without overclaiming.",
      videos: [
        {
          id: "i1",
          title: "Q3 full body paragraph: master the argument essay",
          channel: "YouTube · Nov 2025",
          duration: "18 min",
          url: "https://www.youtube.com/watch?v=JVUlW3TW2A8",
          why: "Covers claim-qualification structure needed for polarizing civic topics — essential for national identity prompts.",
        },
        {
          id: "i2",
          title: "Argument essay guide — how to write your AP Lang essay",
          channel: "College Essay Guy",
          duration: "Long-read",
          url: "https://www.collegeessayguy.com/blog/argument-essay-guide",
          why: "Includes 3 scored 2024 sample essays with rubric commentary; covers civic / identity prompt examples.",
        },
      ],
    },
    {
      id: "energy",
      title: "Energy policy",
      subtitle: "Wind farms & multi-source synthesis",
      lastTested: 2019,
      yearsAbsent: "6+",
      frqType: "Synthesis",
      priority: "HIGH",
      skills: ["CLE", "REO", "RHS"],
      summary: "Multi-source synthesis on energy infrastructure. Demands sustained source evaluation and a defensible line of reasoning across competing perspectives.",
      videos: [
        {
          id: "e1",
          title: "Establishing a line of reasoning — wind farm synthesis",
          channel: "Coach Hall Writes",
          duration: "12 min",
          url: "https://www.youtube.com/watch?v=qvY11BTnv4M",
          why: "Uses the actual 2019 wind farm FRQ — directly on-topic; focuses on REO across multi-source synthesis.",
        },
        {
          id: "e2",
          title: "Synthesis essay instructional video playlist (Q1)",
          channel: "Coach Hall Writes · Playlist",
          duration: "Playlist",
          url: "https://www.youtube.com/playlist?list=PLRC2dgq_mKP_w8BOD36490jsfbzYat4EW",
          why: "Full playlist covering source evaluation, thesis writing, evidence integration, and commentary for synthesis essays.",
        },
        {
          id: "e3",
          title: "How to write a perfect synthesis essay",
          channel: "PrepScholar",
          duration: "Long-read",
          url: "https://blog.prepscholar.com/ap-lang-synthesis-essay",
          why: "Uses the 2019 wind farm prompt as its primary example — full scored sample + rubric breakdown.",
        },
      ],
    },
    {
      id: "eminent",
      title: "Government authority vs. private property",
      subtitle: "Eminent domain synthesis",
      lastTested: 2020,
      yearsAbsent: "5+",
      frqType: "Synthesis",
      priority: "HIGH",
      skills: ["CLE", "REO", "RHS"],
      summary: "Sources actively contradict each other — synthesis must reconcile competing public-good vs. private-rights claims with explicit qualifications.",
      videos: [
        {
          id: "em1",
          title: "Synthesis essay instructional video playlist (Q1)",
          channel: "Coach Hall Writes · Playlist",
          duration: "Playlist",
          url: "https://www.youtube.com/playlist?list=PLRC2dgq_mKP_w8BOD36490jsfbzYat4EW",
          why: "Teaches source evaluation and competing-perspective synthesis — critical when sources actively contradict each other.",
        },
        {
          id: "em2",
          title: "Establishing a line of reasoning — wind farm synthesis",
          channel: "Coach Hall Writes",
          duration: "12 min",
          url: "https://www.youtube.com/watch?v=qvY11BTnv4M",
          why: "REO-focused technique for policy synthesis topics — directly transferable from wind farms to eminent domain framing.",
        },
      ],
    },
    {
      id: "tribute",
      title: "Tribute & eulogy rhetoric",
      subtitle: "Commemorative speech analysis",
      lastTested: 2020,
      yearsAbsent: "5+",
      frqType: "Rhet. Analysis",
      priority: "MED",
      skills: ["RHS", "STY", "CLE"],
      summary: "Epideictic passages where the speaker honors a person or moment. Requires close attention to RHS (speaker–audience–purpose) and stylistic choices that elevate praise.",
      videos: [
        {
          id: "t1",
          title: "Plan with me — rhetorical analysis essay",
          channel: "Coach Hall Writes · May 2021",
          duration: "20 min",
          url: "https://www.youtube.com/watch?v=_yuXUaiBnnA",
          why: "Live outlining session for RA — valuable for understanding how to approach commemorative speeches before writing.",
        },
        {
          id: "t2",
          title: "Rhetorical analysis essay playlist (Q2)",
          channel: "Coach Hall Writes · Playlist",
          duration: "Playlist",
          url: "https://www.youtube.com/playlist?list=PLRC2dgq_mKP81-YSwCYYypDlslGZ5U_8O",
          why: "Full Q2 playlist — includes epideictic / tribute speech analysis techniques relevant to eulogy passage type.",
        },
        {
          id: "t3",
          title: "Teaching the rhetorical situation",
          channel: "Coach Hall Writes",
          duration: "10 min",
          url: "https://www.youtube.com/watch?v=GK0hxznlLxY",
          why: "Understanding speaker-audience-purpose (RHS) is the prerequisite skill for commemorative speech analysis — includes downloadable templates.",
        },
      ],
    },
    {
      id: "labor",
      title: "Historical labor rights",
      subtitle: "Pre-20th century activist speeches",
      lastTested: 2019,
      yearsAbsent: "6+",
      frqType: "Rhet. Analysis",
      priority: "MED",
      skills: ["RHS", "STY", "CLE"],
      summary: "Dense historical passages (e.g. Florence Kelley) demanding annotation of pathos, parallelism, and statistical appeals in service of activist arguments.",
      videos: [
        {
          id: "l1",
          title: "5 tips for teaching rhetorical analysis",
          channel: "Coach Hall Writes",
          duration: "15 min",
          url: "https://www.youtube.com/watch?v=VPWdLIjv_ho",
          why: "Strategies for annotating historical activist speeches — particularly useful for dense pre-20th century passages.",
        },
        {
          id: "l2",
          title: "Rhetorical analysis essay playlist (Q2)",
          channel: "Coach Hall Writes · Playlist",
          duration: "Playlist",
          url: "https://www.youtube.com/playlist?list=PLRC2dgq_mKP81-YSwCYYypDlslGZ5U_8O",
          why: "Covers STY analysis (pathos, parallelism, statistics for emotional effect) — dominant skill set for labor / activist passages.",
        },
      ],
    },
    {
      id: "handwriting",
      title: "Handwriting in the digital age",
      subtitle: "Analog vs. digital synthesis",
      lastTested: 2021,
      yearsAbsent: "4+",
      frqType: "Synthesis",
      priority: "MED",
      skills: ["CLE", "REO", "RHS"],
      summary: "Synthesis prompt mixing cognitive-science research with opinion sources. Requires distinguishing source types and weighting evidence appropriately.",
      videos: [
        {
          id: "h1",
          title: "Synthesis essay instructional video playlist (Q1)",
          channel: "Coach Hall Writes · Playlist",
          duration: "Playlist",
          url: "https://www.youtube.com/playlist?list=PLRC2dgq_mKP_w8BOD36490jsfbzYat4EW",
          why: "Evaluating scientific vs. opinion sources is covered here — key for handwriting synthesis.",
        },
      ],
    },
    {
      id: "perfection",
      title: "Striving for perfection",
      subtitle: "Standards of excellence — argument",
      lastTested: 2021,
      yearsAbsent: "4+",
      frqType: "Argument",
      priority: "MED",
      skills: ["CLE", "REO"],
      summary: "Philosophical prompts demanding nuanced pro/con navigation. Claim qualification is the essential move.",
      videos: [
        {
          id: "p1",
          title: "Q3 full body paragraph: master the argument essay",
          channel: "YouTube · Nov 2025",
          duration: "18 min",
          url: "https://www.youtube.com/watch?v=JVUlW3TW2A8",
          why: "Claim-qualification technique is essential for 'perfection' prompts where students must navigate nuanced pro/con positions.",
        },
        {
          id: "p2",
          title: "2024 AP English Language exam live review",
          channel: "Marco Learning · May 2024",
          duration: "Long",
          url: "https://www.youtube.com/watch?v=vcgBk1fGAxg",
          why: "Full FRQ review including argument essay strategy; covers how to handle philosophical prompts under timed conditions.",
        },
      ],
    },
  ],
};
